use spring_db;

insert into spring_db.products (id, name, price_in_cents) values (1, 'Oribi', 11589);
insert into spring_db.products (id, name, price_in_cents) values (2, 'Weaver, red-billed buffalo', 3160);
insert into spring_db.products (id, name, price_in_cents) values (3, 'Arctic tern', 5074);
insert into spring_db.products (id, name, price_in_cents) values (4, 'Squirrel, red', 3762);
insert into spring_db.products (id, name, price_in_cents) values (5, 'Yak', 6350);
insert into spring_db.products (id, name, price_in_cents) values (6, 'Sun gazer', 3492);
insert into spring_db.products (id, name, price_in_cents) values (7, 'Wolf, common', 6613);
insert into spring_db.products (id, name, price_in_cents) values (8, 'Silver gull', 17126);
insert into spring_db.products (id, name, price_in_cents) values (9, 'Springbuck', 9523);
insert into spring_db.products (id, name, price_in_cents) values (10, 'Monitor, water', 15505);
insert into spring_db.products (id, name, price_in_cents) values (11, 'White-rumped vulture', 14290);
insert into spring_db.products (id, name, price_in_cents) values (12, 'Racer, blue', 15082);
insert into spring_db.products (id, name, price_in_cents) values (13, 'Finch, common melba', 19484);
insert into spring_db.products (id, name, price_in_cents) values (14, 'Weaver, lesser masked', 6222);
insert into spring_db.products (id, name, price_in_cents) values (15, 'North American beaver', 12912);
insert into spring_db.products (id, name, price_in_cents) values (16, 'Sea birds (unidentified)', 4891);
insert into spring_db.products (id, name, price_in_cents) values (17, 'Jackal, asiatic', 2777);
insert into spring_db.products (id, name, price_in_cents) values (18, 'Fox, silver-backed', 18773);
insert into spring_db.products (id, name, price_in_cents) values (19, 'Rat, arboral spiny', 10982);
insert into spring_db.products (id, name, price_in_cents) values (20, 'Blue-tongued skink', 5571);
insert into spring_db.products (id, name, price_in_cents) values (21, 'Red-necked wallaby', 15779);
insert into spring_db.products (id, name, price_in_cents) values (22, 'Teal, hottentot', 1108);
insert into spring_db.products (id, name, price_in_cents) values (23, 'Gemsbok', 5673);
insert into spring_db.products (id, name, price_in_cents) values (24, 'Penguin, little blue', 14377);
insert into spring_db.products (id, name, price_in_cents) values (25, 'Squirrel, eurasian red', 15953);
insert into spring_db.products (id, name, price_in_cents) values (26, 'Goose, greylag', 6046);
insert into spring_db.products (id, name, price_in_cents) values (27, 'Red-winged hawk (unidentified)', 2679);
insert into spring_db.products (id, name, price_in_cents) values (28, 'Little cormorant', 14266);
insert into spring_db.products (id, name, price_in_cents) values (29, 'Greater kudu', 14575);
insert into spring_db.products (id, name, price_in_cents) values (30, 'Bohor reedbuck', 17192);
insert into spring_db.products (id, name, price_in_cents) values (31, 'Pelican, australian', 8610);
insert into spring_db.products (id, name, price_in_cents) values (32, 'Badger, honey', 16245);
insert into spring_db.products (id, name, price_in_cents) values (33, 'Chickadee, black-capped', 18523);
insert into spring_db.products (id, name, price_in_cents) values (34, 'Crab-eating fox', 16718);
insert into spring_db.products (id, name, price_in_cents) values (35, 'Blue shark', 10253);
insert into spring_db.products (id, name, price_in_cents) values (36, 'Paca', 13975);
insert into spring_db.products (id, name, price_in_cents) values (37, 'Black-faced kangaroo', 13702);
insert into spring_db.products (id, name, price_in_cents) values (38, 'Bush dog', 8717);
insert into spring_db.products (id, name, price_in_cents) values (39, 'Cat, tiger', 17040);
insert into spring_db.products (id, name, price_in_cents) values (40, 'Blue-breasted cordon bleu', 6850);
insert into spring_db.products (id, name, price_in_cents) values (41, 'Dove, white-winged', 13323);
insert into spring_db.products (id, name, price_in_cents) values (42, 'Raven, white-necked', 19322);
insert into spring_db.products (id, name, price_in_cents) values (43, 'Southern sea lion', 17845);
insert into spring_db.products (id, name, price_in_cents) values (44, 'Two-toed tree sloth', 8091);
insert into spring_db.products (id, name, price_in_cents) values (45, 'Wolf spider', 13917);
insert into spring_db.products (id, name, price_in_cents) values (46, 'Thirteen-lined squirrel', 10747);
insert into spring_db.products (id, name, price_in_cents) values (47, 'Arctic lemming', 13411);
insert into spring_db.products (id, name, price_in_cents) values (48, 'Swamp deer', 4396);
insert into spring_db.products (id, name, price_in_cents) values (49, 'Porcupine, north american', 18912);
insert into spring_db.products (id, name, price_in_cents) values (50, 'Bat, madagascar fruit', 1427);
insert into spring_db.products (id, name, price_in_cents) values (51, 'Greater sage grouse', 7733);
insert into spring_db.products (id, name, price_in_cents) values (52, 'Antechinus, brown', 10222);
insert into spring_db.products (id, name, price_in_cents) values (53, 'Crab, red lava', 15585);
insert into spring_db.products (id, name, price_in_cents) values (54, 'White-throated robin', 19093);
insert into spring_db.products (id, name, price_in_cents) values (55, 'Bird, black-throated butcher', 16763);
insert into spring_db.products (id, name, price_in_cents) values (56, 'Quail, gambel''s', 8631);
insert into spring_db.products (id, name, price_in_cents) values (57, 'Common green iguana', 5269);
insert into spring_db.products (id, name, price_in_cents) values (58, 'Crane, stanley', 2879);
insert into spring_db.products (id, name, price_in_cents) values (59, 'Phalarope, northern', 5316);
insert into spring_db.products (id, name, price_in_cents) values (60, 'Stick insect', 794);
insert into spring_db.products (id, name, price_in_cents) values (61, 'Hornbill, red-billed', 19098);
insert into spring_db.products (id, name, price_in_cents) values (62, 'Blue-breasted cordon bleu', 14865);
insert into spring_db.products (id, name, price_in_cents) values (63, 'Crane, sandhill', 16732);
insert into spring_db.products (id, name, price_in_cents) values (64, 'Snake, carpet', 8889);
insert into spring_db.products (id, name, price_in_cents) values (65, 'Chickadee, black-capped', 5583);
insert into spring_db.products (id, name, price_in_cents) values (66, 'Fat-tailed dunnart', 19809);
insert into spring_db.products (id, name, price_in_cents) values (67, 'Cockatoo, roseate', 8923);
insert into spring_db.products (id, name, price_in_cents) values (68, 'Ring dove', 1323);
insert into spring_db.products (id, name, price_in_cents) values (69, 'Cockatoo, red-tailed', 4208);
insert into spring_db.products (id, name, price_in_cents) values (70, 'Burmese brown mountain tortoise', 14293);
insert into spring_db.products (id, name, price_in_cents) values (71, 'Kongoni', 1361);
insert into spring_db.products (id, name, price_in_cents) values (72, 'Otter, north american river', 7182);
insert into spring_db.products (id, name, price_in_cents) values (73, 'Pale-throated three-toed sloth', 8630);
insert into spring_db.products (id, name, price_in_cents) values (74, 'Dunnart, fat-tailed', 14190);
insert into spring_db.products (id, name, price_in_cents) values (75, 'Striped hyena', 10377);
insert into spring_db.products (id, name, price_in_cents) values (76, 'Snake, carpet', 16445);
insert into spring_db.products (id, name, price_in_cents) values (77, 'Mountain lion', 1416);
insert into spring_db.products (id, name, price_in_cents) values (78, 'Striped skunk', 13486);
insert into spring_db.products (id, name, price_in_cents) values (79, 'Eagle, crowned', 12066);
insert into spring_db.products (id, name, price_in_cents) values (80, 'Mountain duck', 11913);
insert into spring_db.products (id, name, price_in_cents) values (81, 'Macaw, scarlet', 10923);
insert into spring_db.products (id, name, price_in_cents) values (82, 'Kangaroo, black-faced', 9634);
insert into spring_db.products (id, name, price_in_cents) values (83, 'Skua, great', 14323);
insert into spring_db.products (id, name, price_in_cents) values (84, 'Marabou stork', 5524);
insert into spring_db.products (id, name, price_in_cents) values (85, 'Gazer, sun', 4505);
insert into spring_db.products (id, name, price_in_cents) values (86, 'Chuckwalla', 4190);
insert into spring_db.products (id, name, price_in_cents) values (87, 'Jackal, asiatic', 4185);
insert into spring_db.products (id, name, price_in_cents) values (88, 'Lion, steller sea', 11745);
insert into spring_db.products (id, name, price_in_cents) values (89, 'Pademelon, red-legged', 2977);
insert into spring_db.products (id, name, price_in_cents) values (90, 'Skink, african', 4052);
insert into spring_db.products (id, name, price_in_cents) values (91, 'Two-toed tree sloth', 1521);
insert into spring_db.products (id, name, price_in_cents) values (92, 'Sifaka, verreaux''s', 9892);
insert into spring_db.products (id, name, price_in_cents) values (93, 'Squirrel, smith''s bush', 18770);
insert into spring_db.products (id, name, price_in_cents) values (94, 'Lion, california sea', 15917);
insert into spring_db.products (id, name, price_in_cents) values (95, 'Royal tern', 19458);
insert into spring_db.products (id, name, price_in_cents) values (96, 'African jacana', 19880);
insert into spring_db.products (id, name, price_in_cents) values (97, 'Indian jackal', 16421);
insert into spring_db.products (id, name, price_in_cents) values (98, 'Glider, squirrel', 1165);
insert into spring_db.products (id, name, price_in_cents) values (99, 'Crown of thorns starfish', 7429);
insert into spring_db.products (id, name, price_in_cents) values (100, 'Bee-eater, white-fronted', 16568);